2023-08-25 09:20:44.017 [pool-6-thread-4] ERROR c.d.u.s.YamlSerializerImpl -- Failed to deserialize YAML, Cannot deserialize value of type `java.time.LocalDateTime` from String "2022-12-06T11:58:14.937+00:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2022-12-06T11:58:14.937+00:00' could not be parsed, unparsed text found at index 23 at line 155, column 11, file path: C:\dev\dqo-sample-data\.\sources\kaggle_covidlive\kaggle_covidlive.covid_live.dqotable.yamljava.time.format.DateTimeParseException: Text '2022-12-06T11:58:14.937+00:00' could not be parsed, unparsed text found at index 23
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2055)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:177)
	... 46 common frames omitted
Wrapped by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDateTime` from String "2022-12-06T11:58:14.937+00:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2022-12-06T11:58:14.937+00:00' could not be parsed, unparsed text found at index 23
 at [Source: (StringReader); line: 155, column: 11] (through reference chain: com.dqops.metadata.storage.localfiles.sources.TableYaml["spec"]->com.dqops.metadata.sources.TableSpec["comments"]->com.dqops.metadata.comments.CommentsListSpec[0]->com.dqops.metadata.comments.CommentSpec["date"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:179)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:81)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.DelegatingDeserializer.deserialize(DelegatingDeserializer.java:107)
	at com.dqops.utils.serialization.DeserializationAwareDeserializer.deserialize(DeserializationAwareDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.std.DelegatingDeserializer.deserialize(DelegatingDeserializer.java:107)
	at com.dqops.utils.serialization.DeserializationAwareDeserializer.deserialize(DeserializationAwareDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at com.dqops.utils.serialization.YamlSerializerImpl.deserialize(YamlSerializerImpl.java:129)
	at com.dqops.metadata.storage.localfiles.sources.FileTableWrapperImpl.getSpec(FileTableWrapperImpl.java:91)
	at com.dqops.metadata.storage.localfiles.sources.FileTableWrapperImpl.getSpec(FileTableWrapperImpl.java:38)
	at com.dqops.metadata.basespecs.AbstractElementWrapper$1.lambda$new$0(AbstractElementWrapper.java:36)
	at com.dqops.metadata.id.ChildHierarchyNodeFieldMapImpl.propagateHierarchyIdToChildren(ChildHierarchyNodeFieldMapImpl.java:137)
	at com.dqops.metadata.basespecs.AbstractSpec.propagateHierarchyIdToFields(AbstractSpec.java:108)
	at com.dqops.metadata.basespecs.AbstractSpec.setHierarchyId(AbstractSpec.java:90)
	at com.dqops.metadata.basespecs.AbstractIndexingList.addWithoutFullLoad(AbstractIndexingList.java:186)
	at com.dqops.metadata.storage.localfiles.sources.FileTableListImpl.load(FileTableListImpl.java:58)
	at com.dqops.metadata.basespecs.AbstractIndexingList.loadOnce(AbstractIndexingList.java:298)
	at com.dqops.metadata.basespecs.AbstractIndexingList.iterator(AbstractIndexingList.java:277)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:42)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:43)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:43)
	at com.dqops.metadata.search.HierarchyNodeTreeSearcherImpl.findTables(HierarchyNodeTreeSearcherImpl.java:121)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.listTargetTables(CheckExecutionServiceImpl.java:248)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeChecks(CheckExecutionServiceImpl.java:102)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:75)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:35)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:44.043 [pool-6-thread-4] ERROR c.d.u.s.YamlSerializerImpl -- Failed to deserialize YAML, Cannot deserialize value of type `java.time.LocalDateTime` from String "2022-12-06T12:30:43.816+00:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2022-12-06T12:30:43.816+00:00' could not be parsed, unparsed text found at index 23 at line 84, column 11, file path: C:\dev\dqo-sample-data\.\sources\kaggle_loan\kaggle_loan.eligibility_prediction_for_loan.dqotable.yamljava.time.format.DateTimeParseException: Text '2022-12-06T12:30:43.816+00:00' could not be parsed, unparsed text found at index 23
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2055)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:177)
	... 46 common frames omitted
Wrapped by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDateTime` from String "2022-12-06T12:30:43.816+00:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2022-12-06T12:30:43.816+00:00' could not be parsed, unparsed text found at index 23
 at [Source: (StringReader); line: 84, column: 11] (through reference chain: com.dqops.metadata.storage.localfiles.sources.TableYaml["spec"]->com.dqops.metadata.sources.TableSpec["comments"]->com.dqops.metadata.comments.CommentsListSpec[0]->com.dqops.metadata.comments.CommentSpec["date"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:179)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:81)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.DelegatingDeserializer.deserialize(DelegatingDeserializer.java:107)
	at com.dqops.utils.serialization.DeserializationAwareDeserializer.deserialize(DeserializationAwareDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.std.DelegatingDeserializer.deserialize(DelegatingDeserializer.java:107)
	at com.dqops.utils.serialization.DeserializationAwareDeserializer.deserialize(DeserializationAwareDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at com.dqops.utils.serialization.YamlSerializerImpl.deserialize(YamlSerializerImpl.java:129)
	at com.dqops.metadata.storage.localfiles.sources.FileTableWrapperImpl.getSpec(FileTableWrapperImpl.java:91)
	at com.dqops.metadata.storage.localfiles.sources.FileTableWrapperImpl.getSpec(FileTableWrapperImpl.java:38)
	at com.dqops.metadata.basespecs.AbstractElementWrapper$1.lambda$new$0(AbstractElementWrapper.java:36)
	at com.dqops.metadata.id.ChildHierarchyNodeFieldMapImpl.propagateHierarchyIdToChildren(ChildHierarchyNodeFieldMapImpl.java:137)
	at com.dqops.metadata.basespecs.AbstractSpec.propagateHierarchyIdToFields(AbstractSpec.java:108)
	at com.dqops.metadata.basespecs.AbstractSpec.setHierarchyId(AbstractSpec.java:90)
	at com.dqops.metadata.basespecs.AbstractIndexingList.addWithoutFullLoad(AbstractIndexingList.java:186)
	at com.dqops.metadata.storage.localfiles.sources.FileTableListImpl.load(FileTableListImpl.java:58)
	at com.dqops.metadata.basespecs.AbstractIndexingList.loadOnce(AbstractIndexingList.java:298)
	at com.dqops.metadata.basespecs.AbstractIndexingList.iterator(AbstractIndexingList.java:277)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:42)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:43)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:43)
	at com.dqops.metadata.search.HierarchyNodeTreeSearcherImpl.findTables(HierarchyNodeTreeSearcherImpl.java:121)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.listTargetTables(CheckExecutionServiceImpl.java:248)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeChecks(CheckExecutionServiceImpl.java:102)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:75)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:35)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:44.046 [pool-6-thread-4] ERROR c.d.u.s.YamlSerializerImpl -- Failed to deserialize YAML, Cannot deserialize value of type `java.time.LocalDateTime` from String "2022-12-06T12:37:19.864+00:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2022-12-06T12:37:19.864+00:00' could not be parsed, unparsed text found at index 23 at line 57, column 11, file path: C:\dev\dqo-sample-data\.\sources\kaggle_shirtsizes\kaggle_shirtsizes.shirt_sizes.dqotable.yamljava.time.format.DateTimeParseException: Text '2022-12-06T12:37:19.864+00:00' could not be parsed, unparsed text found at index 23
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2055)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:177)
	... 46 common frames omitted
Wrapped by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDateTime` from String "2022-12-06T12:37:19.864+00:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2022-12-06T12:37:19.864+00:00' could not be parsed, unparsed text found at index 23
 at [Source: (StringReader); line: 57, column: 11] (through reference chain: com.dqops.metadata.storage.localfiles.sources.TableYaml["spec"]->com.dqops.metadata.sources.TableSpec["comments"]->com.dqops.metadata.comments.CommentsListSpec[0]->com.dqops.metadata.comments.CommentSpec["date"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:179)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:81)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.DelegatingDeserializer.deserialize(DelegatingDeserializer.java:107)
	at com.dqops.utils.serialization.DeserializationAwareDeserializer.deserialize(DeserializationAwareDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.std.DelegatingDeserializer.deserialize(DelegatingDeserializer.java:107)
	at com.dqops.utils.serialization.DeserializationAwareDeserializer.deserialize(DeserializationAwareDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at com.dqops.utils.serialization.YamlSerializerImpl.deserialize(YamlSerializerImpl.java:129)
	at com.dqops.metadata.storage.localfiles.sources.FileTableWrapperImpl.getSpec(FileTableWrapperImpl.java:91)
	at com.dqops.metadata.storage.localfiles.sources.FileTableWrapperImpl.getSpec(FileTableWrapperImpl.java:38)
	at com.dqops.metadata.basespecs.AbstractElementWrapper$1.lambda$new$0(AbstractElementWrapper.java:36)
	at com.dqops.metadata.id.ChildHierarchyNodeFieldMapImpl.propagateHierarchyIdToChildren(ChildHierarchyNodeFieldMapImpl.java:137)
	at com.dqops.metadata.basespecs.AbstractSpec.propagateHierarchyIdToFields(AbstractSpec.java:108)
	at com.dqops.metadata.basespecs.AbstractSpec.setHierarchyId(AbstractSpec.java:90)
	at com.dqops.metadata.basespecs.AbstractIndexingList.addWithoutFullLoad(AbstractIndexingList.java:186)
	at com.dqops.metadata.storage.localfiles.sources.FileTableListImpl.load(FileTableListImpl.java:58)
	at com.dqops.metadata.basespecs.AbstractIndexingList.loadOnce(AbstractIndexingList.java:298)
	at com.dqops.metadata.basespecs.AbstractIndexingList.iterator(AbstractIndexingList.java:277)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:42)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:43)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:43)
	at com.dqops.metadata.search.HierarchyNodeTreeSearcherImpl.findTables(HierarchyNodeTreeSearcherImpl.java:121)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.listTargetTables(CheckExecutionServiceImpl.java:248)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeChecks(CheckExecutionServiceImpl.java:102)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:75)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:35)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:44.054 [pool-6-thread-4] ERROR c.d.u.s.YamlSerializerImpl -- Failed to deserialize YAML, Cannot deserialize value of type `java.time.LocalDateTime` from String "2022-12-06T12:39:14.587+00:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2022-12-06T12:39:14.587+00:00' could not be parsed, unparsed text found at index 23 at line 55, column 11, file path: C:\dev\dqo-sample-data\.\sources\kaggle_worldpopulation\kaggle_worldpopulation.world_population_dataset.dqotable.yamljava.time.format.DateTimeParseException: Text '2022-12-06T12:39:14.587+00:00' could not be parsed, unparsed text found at index 23
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2055)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:177)
	... 46 common frames omitted
Wrapped by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDateTime` from String "2022-12-06T12:39:14.587+00:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2022-12-06T12:39:14.587+00:00' could not be parsed, unparsed text found at index 23
 at [Source: (StringReader); line: 55, column: 11] (through reference chain: com.dqops.metadata.storage.localfiles.sources.TableYaml["spec"]->com.dqops.metadata.sources.TableSpec["comments"]->com.dqops.metadata.comments.CommentsListSpec[0]->com.dqops.metadata.comments.CommentSpec["date"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:179)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:81)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.DelegatingDeserializer.deserialize(DelegatingDeserializer.java:107)
	at com.dqops.utils.serialization.DeserializationAwareDeserializer.deserialize(DeserializationAwareDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.std.DelegatingDeserializer.deserialize(DelegatingDeserializer.java:107)
	at com.dqops.utils.serialization.DeserializationAwareDeserializer.deserialize(DeserializationAwareDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at com.dqops.utils.serialization.YamlSerializerImpl.deserialize(YamlSerializerImpl.java:129)
	at com.dqops.metadata.storage.localfiles.sources.FileTableWrapperImpl.getSpec(FileTableWrapperImpl.java:91)
	at com.dqops.metadata.storage.localfiles.sources.FileTableWrapperImpl.getSpec(FileTableWrapperImpl.java:38)
	at com.dqops.metadata.basespecs.AbstractElementWrapper$1.lambda$new$0(AbstractElementWrapper.java:36)
	at com.dqops.metadata.id.ChildHierarchyNodeFieldMapImpl.propagateHierarchyIdToChildren(ChildHierarchyNodeFieldMapImpl.java:137)
	at com.dqops.metadata.basespecs.AbstractSpec.propagateHierarchyIdToFields(AbstractSpec.java:108)
	at com.dqops.metadata.basespecs.AbstractSpec.setHierarchyId(AbstractSpec.java:90)
	at com.dqops.metadata.basespecs.AbstractIndexingList.addWithoutFullLoad(AbstractIndexingList.java:186)
	at com.dqops.metadata.storage.localfiles.sources.FileTableListImpl.load(FileTableListImpl.java:58)
	at com.dqops.metadata.basespecs.AbstractIndexingList.loadOnce(AbstractIndexingList.java:298)
	at com.dqops.metadata.basespecs.AbstractIndexingList.iterator(AbstractIndexingList.java:277)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:42)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:43)
	at com.dqops.metadata.traversal.HierarchyNodeTreeWalkerImpl.traverseHierarchyNodeTree(HierarchyNodeTreeWalkerImpl.java:43)
	at com.dqops.metadata.search.HierarchyNodeTreeSearcherImpl.findTables(HierarchyNodeTreeSearcherImpl.java:121)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.listTargetTables(CheckExecutionServiceImpl.java:248)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeChecks(CheckExecutionServiceImpl.java:102)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:75)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:35)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:46.606 [pool-5-thread-34] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Check runner failed to run checks: Cannot invoke "com.dqops.execution.rules.finder.RuleDefinitionFindResult.getRuleDefinitionSpec()" because "ruleDefinitionFindResult" is nulljava.lang.NullPointerException: Cannot invoke "com.dqops.execution.rules.finder.RuleDefinitionFindResult.getRuleDefinitionSpec()" because "ruleDefinitionFindResult" is null
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:308)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:46.610 [pool-5-thread-34] ERROR c.d.c.jobqueue.BaseDqoJobQueueImpl -- Failed to execute a job: com.dqops.execution.checks.CheckExecutionFailedException: Checks on table failed to executejava.lang.NullPointerException: Cannot invoke "com.dqops.execution.rules.finder.RuleDefinitionFindResult.getRuleDefinitionSpec()" because "ruleDefinitionFindResult" is null
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:308)
	... 11 common frames omitted
Wrapped by: com.dqops.execution.checks.CheckExecutionFailedException: Checks on table failed to execute
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:347)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	... 6 common frames omitted
Wrapped by: com.dqops.core.jobqueue.exceptions.DqoQueueJobExecutionException: com.dqops.execution.checks.CheckExecutionFailedException: Checks on table failed to execute
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:139)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:47.636 [pool-5-thread-6] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 67, in evaluate_rule
    filtered = [readouts.sensor_readout for readouts in rule_parameters.previous_readouts if readouts is not None]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'previous_readouts'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 67, in evaluate_rule
    filtered = [readouts.sensor_readout for readouts in rule_parameters.previous_readouts if readouts is not None]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'previous_readouts'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:48.841 [pool-5-thread-14] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 67, in evaluate_rule
    filtered = [readouts.sensor_readout for readouts in rule_parameters.previous_readouts if readouts is not None]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'previous_readouts'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 67, in evaluate_rule
    filtered = [readouts.sensor_readout for readouts in rule_parameters.previous_readouts if readouts is not None]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'previous_readouts'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:55.879 [pool-5-thread-24] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:55.892 [pool-5-thread-24] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:55.895 [pool-5-thread-24] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 67, in evaluate_rule
    filtered = [readouts.sensor_readout for readouts in rule_parameters.previous_readouts if readouts is not None]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'previous_readouts'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 67, in evaluate_rule
    filtered = [readouts.sensor_readout for readouts in rule_parameters.previous_readouts if readouts is not None]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'previous_readouts'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:55.924 [pool-5-thread-24] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 67, in evaluate_rule
    filtered = [readouts.sensor_readout for readouts in rule_parameters.previous_readouts if readouts is not None]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'previous_readouts'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 67, in evaluate_rule
    filtered = [readouts.sensor_readout for readouts in rule_parameters.previous_readouts if readouts is not None]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'previous_readouts'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:20:58.779 [pool-6-thread-4] ERROR c.d.c.jobqueue.BaseDqoJobQueueImpl -- Failed to execute a job: com.dqops.core.jobqueue.exceptions.DqoQueueJobExecutionException: com.dqops.execution.checks.CheckExecutionFailedException: Checks on table failed to executejava.lang.NullPointerException: Cannot invoke "com.dqops.execution.rules.finder.RuleDefinitionFindResult.getRuleDefinitionSpec()" because "ruleDefinitionFindResult" is null
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:308)
	... 11 common frames omitted
Wrapped by: com.dqops.execution.checks.CheckExecutionFailedException: Checks on table failed to execute
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:347)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	... 7 common frames omitted
Wrapped by: com.dqops.core.jobqueue.exceptions.DqoQueueJobExecutionException: com.dqops.execution.checks.CheckExecutionFailedException: Checks on table failed to execute
	at com.dqops.core.jobqueue.ChildDqoQueueJobsContainer.waitForChildResults(ChildDqoQueueJobsContainer.java:139)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeChecks(CheckExecutionServiceImpl.java:127)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:75)
	at com.dqops.execution.checks.jobs.RunChecksQueueJob.onExecute(RunChecksQueueJob.java:35)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	... 6 common frames omitted
Wrapped by: com.dqops.core.jobqueue.exceptions.DqoQueueJobExecutionException: com.dqops.core.jobqueue.exceptions.DqoQueueJobExecutionException: com.dqops.execution.checks.CheckExecutionFailedException: Checks on table failed to execute
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:139)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:21:27.522 [pool-5-thread-5] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:21:28.463 [pool-5-thread-18] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:21:37.140 [pool-5-thread-36] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:21:37.281 [pool-5-thread-36] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:21:37.300 [pool-5-thread-36] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:21:37.471 [pool-5-thread-36] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:26:45.569 [pool-5-thread-26] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:26:47.009 [pool-5-thread-44] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:26:53.790 [pool-5-thread-20] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:26:53.798 [pool-5-thread-20] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:26:53.800 [pool-5-thread-20] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:26:53.810 [pool-5-thread-20] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:28:01.226 [pool-5-thread-29] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:28:01.240 [pool-5-thread-29] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:28:01.249 [pool-5-thread-29] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:28:01.253 [pool-5-thread-29] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:32:19.538 [pool-5-thread-9] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:33:42.544 [pool-5-thread-50] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:33:58.782 [pool-5-thread-14] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:33:58.803 [pool-5-thread-14] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:33:58.808 [pool-5-thread-14] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:34:18.886 [pool-5-thread-41] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:34:19.854 [pool-5-thread-5] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:34:23.281 [pool-5-thread-46] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:34:23.283 [pool-5-thread-46] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:34:23.292 [pool-5-thread-46] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:35:10.901 [pool-5-thread-48] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:35:12.852 [pool-5-thread-26] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:35:13.319 [pool-5-thread-32] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule comparison/equals_integer failed to execute: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\comparison\equals_integer.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\comparison\equals_integer.py", line 67, in evaluate_rule
    expected_value = rule_parameters.parameters.expected_value
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ObjectHook' object has no attribute 'expected_value'

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:35:13.326 [pool-5-thread-32] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:35:13.331 [pool-5-thread-32] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:55:49.434 [pool-5-thread-44] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:55:50.737 [pool-5-thread-20] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:55:52.317 [pool-5-thread-5] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:202)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-08-25 09:55:52.322 [pool-5-thread-5] ERROR c.d.e.c.TableCheckExecutionServiceImpl -- Rule change/change_percent failed to execute: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range
com.dqops.utils.python.PythonExecutionException: Data quality rule C:\dev\dqoado\home\rules\change\change_percent.py failed to execute, error: Traceback (most recent call last):
  File "C:\dev\dqoado\home\lib\evaluate_rules.py", line 91, in process_rule_request
    rule_result = rule_function(rule_parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\dqoado\home\rules\change\change_percent.py", line 68, in evaluate_rule
    previous_readout = filtered[0]
                       ~~~~~~~~^^^
IndexError: list index out of range

	at com.dqops.execution.rules.runners.python.PythonRuleRunner.executeRule(PythonRuleRunner.java:83)
	at com.dqops.execution.rules.DataQualityRuleRunnerImpl.executeRule(DataQualityRuleRunnerImpl.java:66)
	at com.dqops.execution.checks.ruleeval.RuleEvaluationServiceImpl.evaluateRules(RuleEvaluationServiceImpl.java:227)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeSingleTableChecks(TableCheckExecutionServiceImpl.java:322)
	at com.dqops.execution.checks.TableCheckExecutionServiceImpl.executeChecksOnTable(TableCheckExecutionServiceImpl.java:204)
	at com.dqops.execution.checks.CheckExecutionServiceImpl.executeSelectedChecksOnTable(CheckExecutionServiceImpl.java:233)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:82)
	at com.dqops.execution.checks.jobs.RunChecksOnTableQueueJob.onExecute(RunChecksOnTableQueueJob.java:37)
	at com.dqops.core.jobqueue.DqoQueueJob.execute(DqoQueueJob.java:125)
	at com.dqops.core.jobqueue.BaseDqoJobQueueImpl.jobProcessingThreadLoop(BaseDqoJobQueueImpl.java:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

